name: Liquibase Deploy

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Optional: quick validation (doesn't change DB)
      - name: Liquibase validate
        env:
          RDS_ENDPOINT:  ${{ secrets.RDS_ENDPOINT }}     # e.g. database-1....rds.amazonaws.com
          RDS_DBNAME:    ${{ secrets.RDS_DBNAME }}       # e.g. sample_liquibase
          RDS_USERNAME:  ${{ secrets.RDS_USERNAME }}     # e.g. liquibase_user (or admin)
          RDS_PASSWORD:  ${{ secrets.RDS_PASSWORD }}
        run: |
          mvn -B org.liquibase:liquibase-maven-plugin:4.27.0:validate \
            -Dliquibase.url="jdbc:postgresql://${RDS_ENDPOINT}:5432/${RDS_DBNAME}?sslmode=require" \
            -Dliquibase.username="${RDS_USERNAME}" \
            -Dliquibase.password="${RDS_PASSWORD}" \
            -Dliquibase.changeLogFile="src/main/resources/db/changelog/db.changelog-master.yaml"

      - name: Liquibase update (apply changes)
        env:
          RDS_ENDPOINT:  ${{ secrets.RDS_ENDPOINT }}
          RDS_DBNAME:    ${{ secrets.RDS_DBNAME }}
          RDS_USERNAME:  ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD:  ${{ secrets.RDS_PASSWORD }}
        run: |
          mvn -B org.liquibase:liquibase-maven-plugin:4.27.0:update \
            -Dliquibase.url="jdbc:postgresql://${RDS_ENDPOINT}:5432/${RDS_DBNAME}?sslmode=require" \
            -Dliquibase.username="${RDS_USERNAME}" \
            -Dliquibase.password="${RDS_PASSWORD}" \
            -Dliquibase.changeLogFile="src/main/resources/db/changelog/db.changelog-master.yaml"

      # Optional: show history after update
      - name: Liquibase history (report)
        env:
          RDS_ENDPOINT:  ${{ secrets.RDS_ENDPOINT }}
          RDS_DBNAME:    ${{ secrets.RDS_DBNAME }}
          RDS_USERNAME:  ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD:  ${{ secrets.RDS_PASSWORD }}
        run: |
          mvn -B org.liquibase:liquibase-maven-plugin:4.27.0:history \
            -Dliquibase.url="jdbc:postgresql://${RDS_ENDPOINT}:5432/${RDS_DBNAME}?sslmode=require" \
            -Dliquibase.username="${RDS_USERNAME}" \
            -Dliquibase.password="${RDS_PASSWORD}" \
            -Dliquibase.changeLogFile="src/main/resources/db/changelog/db.changelog-master.yaml"
